[package]
name = "ash-by-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = {version = "0.37", default-features = false, features = ["debug"]}
ash-window = "0.12.0"
# ash-window currently only works with raw-window-handle 0.5.0
raw-window-handle = "0.5.0"
# because raw-window-handle is 0.5.0, disable the rwh_06 feature and enable rwh_05
winit = {version = "0.29.10", default-features = false, features = ["rwh_05", "x11", "wayland", "wayland-dlopen", "wayland-csd-adwaita"]}
log = {version = "0.4"}
env_logger = "0.11.0"
image = "0.24.8"
memoffset = "0.9.0"
rand = "0.8.5"

[features]
"default" = ["load", "vl"]
"load" = ["ash/loaded"]
"link" = ["ash/linked"]
"vl" = []