[package]
name = "ash-by-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = {version = "0.37", default-features = false, features = ["debug"]}
log = {version = "0.4"}
env_logger = "0.11.0"
image = "0.24.8"
thiserror = "1"

[features]
"default" = ["load", "vl"]
"load" = ["ash/loaded"]
"link" = ["ash/linked"]
"vl" = []
